// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Brand struct {
	Name    string `json:"name"`
	Country string `json:"country"`
}

type Mobile struct {
	ModelID string `json:"modelID"`
	Name    string `json:"name"`
	Os      string `json:"os"`
	Country string `json:"country"`
	Brand   *Brand `json:"brand"`
}

type Mutation struct {
}

type NewMobile struct {
	Name  string `json:"name"`
	Brand string `json:"brand"`
}

type Query struct {
}
